# Site settings
title: My life at Perffy
email: oscar@perffy.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about my days as CEO of Perffy, the social network
  for the entertainment business.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://perffy.com" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
# twitter:  username
# weibo:    ID
# github:   username
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
